// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gleipnir/v1/gleipnir.proto

package gleipnirv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VendRequest identifies the connection to vend and the owner asserting access.
type VendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// owner is the opaque owner key the trusted caller asserts.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// connection_id is the connection to vend a secret for.
	ConnectionId  string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendRequest) Reset() {
	*x = VendRequest{}
	mi := &file_gleipnir_v1_gleipnir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendRequest) ProtoMessage() {}

func (x *VendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gleipnir_v1_gleipnir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendRequest.ProtoReflect.Descriptor instead.
func (*VendRequest) Descriptor() ([]byte, []int) {
	return file_gleipnir_v1_gleipnir_proto_rawDescGZIP(), []int{0}
}

func (x *VendRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *VendRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// VendResponse carries the secret material relevant to the connector's auth
// type. OAuth connectors populate access_token; API-key connectors populate
// api_key and api_secret.
type VendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// access_token is the OAuth bearer token (empty for API-key connectors).
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// api_key is the API key (empty for OAuth connectors).
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// api_secret is the API secret (empty for OAuth connectors).
	ApiSecret string `protobuf:"bytes,3,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	// expires_at is when the vended secret expires, if known.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// fields carries the credential material that does not fit the two-string
	// API-key shape.
	//
	// Some venues need more than a key and a secret to open a session: Tradovate
	// wants an account login, an API key pair, a stable device id and an
	// application identifier, and a FIX session wants sender and target comp ids.
	// Packing those into api_secret as an encoded blob would put structure inside
	// a string that nothing validates, and adding a named field per venue would
	// make this message grow with the connector catalog.
	//
	// Gleipnir does not interpret these. It seals them, vends them back, and the
	// connector-specific adapter on the other side is what knows the names it
	// needs — which is also what keeps venue vocabulary out of the credential
	// store.
	Fields map[string]string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// connector is the connector slug this connection belongs to — "tradovate",
	// "coinbase", "ibkr-flex".
	//
	// It is here because the caller needs it and asking separately would mean a
	// second round trip to learn something this response already knows. A trading
	// runner holding a connection id has to decide which venue adapter to build
	// before it can use the secret at all, and the alternative to being told is
	// guessing — either by trying adapters until one authenticates, or by keeping
	// its own copy of which connection is which, which is a second answer that can
	// disagree with this one.
	//
	// Not secret. It is returned on the S2S path only because that is where the
	// rest of this message goes.
	Connector     string `protobuf:"bytes,6,opt,name=connector,proto3" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendResponse) Reset() {
	*x = VendResponse{}
	mi := &file_gleipnir_v1_gleipnir_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendResponse) ProtoMessage() {}

func (x *VendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gleipnir_v1_gleipnir_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendResponse.ProtoReflect.Descriptor instead.
func (*VendResponse) Descriptor() ([]byte, []int) {
	return file_gleipnir_v1_gleipnir_proto_rawDescGZIP(), []int{1}
}

func (x *VendResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VendResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *VendResponse) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *VendResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *VendResponse) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *VendResponse) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

var File_gleipnir_v1_gleipnir_proto protoreflect.FileDescriptor

const file_gleipnir_v1_gleipnir_proto_rawDesc = "" +
	"\n" +
	"\x1agleipnir/v1/gleipnir.proto\x12\vgleipnir.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\vVendRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\"\xbc\x02\n" +
	"\fVendResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x03 \x01(\tR\tapiSecret\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12=\n" +
	"\x06fields\x18\x05 \x03(\v2%.gleipnir.v1.VendResponse.FieldsEntryR\x06fields\x12\x1c\n" +
	"\tconnector\x18\x06 \x01(\tR\tconnector\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012K\n" +
	"\fTokenService\x12;\n" +
	"\x04Vend\x12\x18.gleipnir.v1.VendRequest\x1a\x19.gleipnir.v1.VendResponseB\xb3\x01\n" +
	"\x0fcom.gleipnir.v1B\rGleipnirProtoP\x01ZDgithub.com/fromforgesoftware/gleipnir/pkg/api/gleipnir/v1;gleipnirv1\xa2\x02\x03GXX\xaa\x02\vGleipnir.V1\xca\x02\vGleipnir\\V1\xe2\x02\x17Gleipnir\\V1\\GPBMetadata\xea\x02\fGleipnir::V1b\x06proto3"

var (
	file_gleipnir_v1_gleipnir_proto_rawDescOnce sync.Once
	file_gleipnir_v1_gleipnir_proto_rawDescData []byte
)

func file_gleipnir_v1_gleipnir_proto_rawDescGZIP() []byte {
	file_gleipnir_v1_gleipnir_proto_rawDescOnce.Do(func() {
		file_gleipnir_v1_gleipnir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gleipnir_v1_gleipnir_proto_rawDesc), len(file_gleipnir_v1_gleipnir_proto_rawDesc)))
	})
	return file_gleipnir_v1_gleipnir_proto_rawDescData
}

var file_gleipnir_v1_gleipnir_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gleipnir_v1_gleipnir_proto_goTypes = []any{
	(*VendRequest)(nil),           // 0: gleipnir.v1.VendRequest
	(*VendResponse)(nil),          // 1: gleipnir.v1.VendResponse
	nil,                           // 2: gleipnir.v1.VendResponse.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_gleipnir_v1_gleipnir_proto_depIdxs = []int32{
	3, // 0: gleipnir.v1.VendResponse.expires_at:type_name -> google.protobuf.Timestamp
	2, // 1: gleipnir.v1.VendResponse.fields:type_name -> gleipnir.v1.VendResponse.FieldsEntry
	0, // 2: gleipnir.v1.TokenService.Vend:input_type -> gleipnir.v1.VendRequest
	1, // 3: gleipnir.v1.TokenService.Vend:output_type -> gleipnir.v1.VendResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gleipnir_v1_gleipnir_proto_init() }
func file_gleipnir_v1_gleipnir_proto_init() {
	if File_gleipnir_v1_gleipnir_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gleipnir_v1_gleipnir_proto_rawDesc), len(file_gleipnir_v1_gleipnir_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gleipnir_v1_gleipnir_proto_goTypes,
		DependencyIndexes: file_gleipnir_v1_gleipnir_proto_depIdxs,
		MessageInfos:      file_gleipnir_v1_gleipnir_proto_msgTypes,
	}.Build()
	File_gleipnir_v1_gleipnir_proto = out.File
	file_gleipnir_v1_gleipnir_proto_goTypes = nil
	file_gleipnir_v1_gleipnir_proto_depIdxs = nil
}
