// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gleipnir/v1/gleipnir.proto

package gleipnirv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenService_Vend_FullMethodName = "/gleipnir.v1.TokenService/Vend"
)

// TokenServiceClient is the client API for TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenService vends a connection's current provider secret to trusted backend
// callers (service-to-service). The caller passes the connection's owner; a
// mismatch yields not-found, never a secret. Refresh tokens never cross the
// wire — they stay sealed inside Gleipnir.
type TokenServiceClient interface {
	// Vend returns the connection's current secret, transparently refreshing it
	// when it is within the refresh lead of expiry.
	Vend(ctx context.Context, in *VendRequest, opts ...grpc.CallOption) (*VendResponse, error)
}

type tokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenServiceClient(cc grpc.ClientConnInterface) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) Vend(ctx context.Context, in *VendRequest, opts ...grpc.CallOption) (*VendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VendResponse)
	err := c.cc.Invoke(ctx, TokenService_Vend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServiceServer is the server API for TokenService service.
// All implementations should embed UnimplementedTokenServiceServer
// for forward compatibility.
//
// TokenService vends a connection's current provider secret to trusted backend
// callers (service-to-service). The caller passes the connection's owner; a
// mismatch yields not-found, never a secret. Refresh tokens never cross the
// wire — they stay sealed inside Gleipnir.
type TokenServiceServer interface {
	// Vend returns the connection's current secret, transparently refreshing it
	// when it is within the refresh lead of expiry.
	Vend(context.Context, *VendRequest) (*VendResponse, error)
}

// UnimplementedTokenServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenServiceServer struct{}

func (UnimplementedTokenServiceServer) Vend(context.Context, *VendRequest) (*VendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Vend not implemented")
}
func (UnimplementedTokenServiceServer) testEmbeddedByValue() {}

// UnsafeTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServiceServer will
// result in compilation errors.
type UnsafeTokenServiceServer interface {
	mustEmbedUnimplementedTokenServiceServer()
}

func RegisterTokenServiceServer(s grpc.ServiceRegistrar, srv TokenServiceServer) {
	// If the following call panics, it indicates UnimplementedTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenService_ServiceDesc, srv)
}

func _TokenService_Vend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).Vend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_Vend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).Vend(ctx, req.(*VendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenService_ServiceDesc is the grpc.ServiceDesc for TokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gleipnir.v1.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vend",
			Handler:    _TokenService_Vend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gleipnir/v1/gleipnir.proto",
}
