{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gleipnir.dbSecretName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "gleipnir.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
{{- end }}
{{- if and (not .Values.vault.existingSecret) (not .Values.vault.kmsKey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gleipnir.vaultSecretName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "gleipnir.labels" . | nindent 4 }}
type: Opaque
stringData:
  GLEIPNIR_KEY_ENCRYPTION_KEY: {{ required "vault.keyEncryptionKey or vault.existingSecret is required" .Values.vault.keyEncryptionKey | quote }}
{{- end }}
{{- if and .Values.oauth.connectors (not .Values.oauth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gleipnir.oauthSecretName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "gleipnir.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.oauth.connectors }}
  GLEIPNIR_OAUTH_{{ .slug | upper }}_CLIENT_ID: {{ .clientId | quote }}
  GLEIPNIR_OAUTH_{{ .slug | upper }}_CLIENT_SECRET: {{ .clientSecret | quote }}
  {{- end }}
{{- end }}
