replicaCount: 1

image:
  pullPolicy: IfNotPresent

database:
  host: postgres
  port: '5432'
  name: forge
  schema: gleipnir
  ssl: disable
  username: forge
  password: forge

# Local-only KEK (non-production).
vault:
  keyEncryptionKey: '24ckN78VPMEKDbrgVMEZUwtn5vIswCulIphK+666KWI='

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: '1'
    memory: 512Mi

gatewaySecret: dev-forge-gateway-secret
